---
- name: "Update iKonoSuite"
  hosts: Voice:Apps:!B2BUA:!CentOS5:!Skipped
  tasks:
    # # Update servers
    # - import_tasks: tasks/update-all-packages.yml

    - import_tasks: tasks/install-packages-required.yml
      when: "'Apps' in group_names"

    # Update services
    - import_tasks: tasks/update-database.yml
      when: "'Apps' in group_names"

    - import_tasks: tasks/update-execs.yml
      when: "'Voice' in group_names"

    - import_tasks: tasks/update-cmqueuelog.yml
      when: "'Voice' in group_names"

    - import_tasks: tasks/update-cmrecording.yml
      when: "'Voice' in group_names"

    # Config servers
    - import_tasks: tasks/add-ikonosuite-user.yml

    - import_tasks: tasks/dirs-setup.yml
      when: "'Voice' in group_names"
    
    - import_tasks: tasks/create-virtual-envs.yml
      become: yes
      become_method: su
      become_user: ikono
      when: "'Apps' in group_names"

    # Config ip_mapping
    - import_tasks: tasks/config-ip-mapping.yml
      when: "'Apps' in group_names"

    # Install Web
    - import_tasks: tasks/install-web.yml
      become: yes
      become_method: su
      become_user: ikono
      when: "'Apps' in group_names"
    
    # Config Database
    - import_tasks: tasks/config-database.yml
      when: "'Apps' in group_names"

    - import_tasks: tasks/migrations-django.yml
      become: yes
      become_method: su
      become_user: ikono
      when: "'Apps' in group_names"

    # Config Webserver
    - import_tasks: tasks/config-webserver.yml
      when: "'Apps' in group_names"

    # Config CTI-API
    - import_tasks: tasks/install-cti-api.yml
      when: "'Apps' in group_names"

    # Add docker networks
    - import_tasks: tasks/config-docker-networks.yml
      when: "'Voice' in group_names"

    # Config Services
    - import_tasks: tasks/config-services.yml
      when: "'Apps' in group_names"

    # Update repositories
    - import_tasks: tasks/update-cti-api.yml
      when: "'Apps' in group_names"
    
    ## Start docker and cti-api
    #- import_tasks: tasks/start-services-cti-api.yml
    #  when: "'Apps' in group_names"

    - import_tasks: tasks/update-backend.yml
      become: yes
      become_method: su
      become_user: ikono
      when: "'Apps' in group_names"
      
    ## Migration new plataform
    #- import_tasks: tasks/config-sounds.yml
    #  when: "'Voice' in group_names"

    #- import_tasks: tasks/copy-sounds.yml
    #  become: yes
    #  become_method: su
    #  become_user: ikono
    #  when: "'Apps' in group_names"

    #- import_tasks: tasks/config-database-migration.yml
    #  when: "'Apps' in group_names"

    #- import_tasks: tasks/config-users-and-reports.yml
    #  become: yes
    #  become_method: su
    #  become_user: ikono
    #  when: "'Apps' in group_names"

    #- import_tasks: tasks/config-shifts.yml
    #  when: "'Apps' in group_names"
    #
    ## NOTA: -e "product_ikono='pbx-call'"
    #- import_tasks: tasks/config-webserver-migration.yml
    #  when: "'Apps' in group_names"

    ##- import_tasks: tasks/config-webserver-ports.yml
    ##  when: "'Apps' in group_names"
    ### End Migration new plataform

    - import_tasks: tasks/check-services.yml
      when: "'Apps' in group_names"

    - import_tasks: tasks/download-ikono-suite-backup.yml
    #  when: "'Voice' in group_names"

  handlers: 
    - import_tasks: handlers/supervisorctl.yml
    - import_tasks: handlers/webserver.yml
      
  vars_files: 
    - vars/subversion.yml
    - vars/mysql.yml
    - vars/ikono.yml
    - vars/gitlab.yml
    - vars/api.yml
    - vars/django.yml
    - vars/directories.yml
