---
- name: "Update iKonoSuite"
  #hosts: all
  hosts: all:!B2BUA:!CentOS5
  tasks:
    #- import_tasks: tasks/update-all-packages.yml
    #- import_tasks: tasks/install-packages-required.yml
    - import_tasks: tasks/prepare-server-to-update.yml
  vars_files: 
    - vars/subversion.yml