---
- name: "Update iKonoSuite"
  hosts: all:!B2BUA:!CentOS5:!Migrated:!MarketingPersonal:!MillanAsociados:!Surtiplas:!TecnodieselPasto:!METGroup
  vars_files: 
    - vars/subversion.yml
    - vars/mysql.yml
    - vars/ikono.yml
  tasks:

    # - import_tasks: tasks/update-all-packages.yml

    # - import_tasks: tasks/install-packages-required.yml

    # - import_tasks: tasks/update-database.yml
    #   when: "'apps' in group_names"
    
    # - import_tasks: tasks/update-execs.yml
    #   when: "'voice' in group_names"
    
    # - import_tasks: tasks/update-cmqueuelog.yml
    #   when: "'voice' in group_names"

    ## NOTE: Verify local changes in nodes
    # - import_tasks: tasks/update-cmrecording.yml
    #  when: "'voice' in group_names"

    # - import_tasks: tasks/add-ikonosuite-user.yml

    # - import_tasks: tasks/dirs-setup.yml
    #   when: "'voice' in group_names"

    ### Here we go!. 
