---
- name: "Update iKonoSuite"
  #hosts: all
  #hosts: all:!B2BUA:!CentOS5

  ### Update OS and Install packages required... excepciones
  #hosts: all:!B2BUA:!CentOS5:!MarketingPersonal:!MillanAsociados:!RapidoOchoa:!Surtiplas:!TecnodieselPasto
  
  ### CMqueuelog... exepciones
  hosts: all:!B2BUA:!CentOS5:!MarketingPersonal:!MillanAsociados:!RapidoOchoa:!Surtiplas:!TecnodieselPasto!METGroup

  tasks:

    # - import_tasks: tasks/update-all-packages.yml

    # - import_tasks: tasks/install-packages-required.yml

    # - import_tasks: tasks/update-database.yml
    #   when: "'apps' in group_names"
    
    # - import_tasks: tasks/update-execs.yml
    #   when: "'voice' in group_names"
    
    # - import_tasks: tasks/update-cmqueuelog.yml
    #   when: "'voice' in group_names"

    ### Here we go!. 

    - import_tasks: tasks/update-cmrecording.yml
      when: "'voice' in group_names"
  
    # - import_tasks: tasks/update-monitor-args-agi.yml
    #   when: "'voice' in group_names"

  vars_files: 
    - vars/subversion.yml
    - vars/mysql.yml
