# export ANSIBLE_HOST_KEY_CHECKING=False
# ansible-playbook deploy_authorized_keys.yml --ask-become-pass --ask-pass --extra-vars='pubkey="<pubkey-for-super-user>”’
# ansible-playbook playbooks/ssh.yml --ask-pass

- name: "add SSH authorized keys"
  authorized_key:
    user: root
    state: present # present / absent
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  #   key: "{{ item }}"
  # with_file:
  #   - /home/user/.ssh/id_rsa.pub
  #   - /home/user/.ssh/id_rsa_other.pub
