- name: "Create /ikono redirect"
  file:
    path: /var/www/html/ikono
    state: directory

- name: "Copy index.php file for redirect to nginx"
  copy:
    src: files/nginx_ikono_index.php
    dest: /var/www/html/ikono/index.php
    force: no

- name: "Config product port for nginx"
  shell:
    cmd: | 
      cd /home/ikono/web/
      PRODUCT='{{ product_ikono }}'
      if [[ $(grep "['\"]pbx-call[\"']" ikono_suite_backend/ikono_suite/local_settings.py build_ikono_suite_frontend/assets/config/config.deploy.json) ]]; then
        sed -i "s/\(['\"]\)pbx-call\([\"']\)/\1${PRODUCT}\2/g" ikono_suite_backend/ikono_suite/local_settings.py build_ikono_suite_frontend/assets/config/config.deploy.json
      else
        echo "OK"
      fi
  register: config_default_nginx
  changed_when: config_default_nginx.stdout != "OK"
  vars: 
    product_ikono: "pbx-call"
  notify: supervisorctl_ikono_suite_restart
