- name: "chmod in asterisk directories"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: g+w
    group: root
  loop: 
    - /var/lib/asterisk/moh
    - /var/lib/asterisk/sounds/custom
    - /etc/asterisk/
    - /tftpboot/