- name: "Update execs scripts"
  subversion:
    repo: http://dev.ikono.com.co/svn/execs/trunk
    dest: /etc/asterisk/execs
    username: "{{ username }}"
    password: "{{ password }}"
    checkout: no
    update: yes
    switch: no
    force: no

- name: "Backup cmqueuelog config"
  synchronize:
    src: /etc/cmqueuelog/
    dest: /tmp/cmqueuelog_{{ ansible_date_time.date }}
  delegate_to: "{{ inventory_hostname }}"
  register: cmqueuelog_backup

- name: "Update cmqueuelog sources"
  subversion:
    repo: http://dev.ikono.com.co/svn/queuelog/trunk
    dest: /usr/local/src/ikono/queuelog-trunk
    username: "{{ username }}"
    password: "{{ password }}"
    checkout: no
    update: yes
    switch: no
    force: no
  register: cmqueuelog_update

- name: "Install cmqueuelog from sources"
  shell: 
    cmd: |
      cd /usr/local/src/ikono/queuelog-trunk/
      python setup.py install
      service cmqueuelog restart
    chdir: /usr/local/src/python/Python-3.8.2/
  register: install_python
  when: cmqueuelog_update is changed

- name: "Checking cmqueuelog running"
  service:
    name: cmqueuelog
    state: started

