### CM-Queuelog

- name: "Backup cmqueuelog config"
  synchronize:
    src: /etc/cmqueuelog/
    dest: /tmp/cmqueuelog_{{ ansible_date_time.epoch }}
  delegate_to: "{{ inventory_hostname }}"
  register: cmqueuelog_backup

- name: "Update cmqueuelog sources"
  subversion:
    repo: http://dev.ikono.com.co/svn/queuelog/trunk
    dest: /usr/local/src/ikono/queuelog-trunk
    username: "{{ svn_username }}"
    password: "{{ svn_password }}"
    checkout: no
    update: yes
    switch: no
    force: no
  register: cmqueuelog_update

- name: "Install cmqueuelog from sources"
  shell: 
    cmd: |
      python setup.py install
      HOST=$(grep -E "host =.*" /tmp/cmqueuelog_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]*/cmqueuelog.conf | awk '{print $3}' | head -n1)
      sed -i.$(date +"%s") "s/\(host =\).*/\1 $HOST/g" /etc/cmqueuelog/cmqueuelog.conf
      service cmqueuelog restart
    chdir: /usr/local/src/ikono/queuelog-trunk/
  when: cmqueuelog_update is changed

- name: "Checking cmqueuelog running"
  service:
    name: cmqueuelog
    state: started

- name: "Validate cmqueuelog updated"
  shell: 
    cmd: |
      if [[ -e /usr/local/lib/python2.7/site-packages/queuelog/ ]]; then
        grep "# if total_tally > 0:" /usr/local/lib/python2.7/site-packages/queuelog/db.py
      elif [[ -e /usr/lib/python2.7/site-packages/queuelog/ ]]; then
        grep "# if total_tally > 0:" /usr/lib/python2.7/site-packages/queuelog/db.py
      fi
  register: cmqueuelog_version
  failed_when: cmqueuelog_version.stdout == ""
