### Monitor args AGI

- name: "Backup monitor-args config"
  synchronize:
    src: /usr/local/src/agis/agi-monitor-args-trunk/
    dest: /tmp/monitor-args_{{ ansible_date_time.epoch }}
  delegate_to: "{{ inventory_hostname }}"

- name: "Update monitor-args AGI"
  subversion:
    repo: http://dev.ikono.com.co/svn/agis/agi_monitor-args/trunk
    dest: /usr/local/src/agis/agi-monitor-args-trunk
    username: "{{ svn_username }}"
    password: "{{ svn_password }}"
    checkout: no
    update: yes
    switch: no
    force: yes

- name: "Config monitor-args.py script updated"
  shell:
    cmd: |
      HOST=$(grep -E "_HOST'][ ]*=[ ]*['\"]" /tmp/monitor-args_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]*/monitor-args.py | cut -d'=' -f2 | sed "s/[ '\"]//g" | head -n1)
      USE_TALLY=$(grep -E "USE_TALLY'][ ]*=[ ]*" /tmp/monitor-args_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]*/monitor-args.py | grep -Eio "True|False")
      USE_CTI=$(grep -E "USE_CTI'][ ]*=[ ]*" /tmp/monitor-args_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]*/monitor-args.py | grep -Eio "True|False")
      sed -i.$(date +"%s") "
      s#/usr/bin/env python#$(which python)#g
      s/\(_HOST'][ ]*=[ ]*['\"]\).*/\1${HOST}'/g
      s/\(USE_TALLY'][ ]*=[ ]*\).*/\1${USE_TALLY}/g
      s/\(USE_CTI'][ ]*=[ ]*\).*/\1${USE_CTI}/g
      " monitor-args.py
      grep $HOST monitor-args.py
    chdir: /usr/local/src/agis/agi-monitor-args-trunk
  register: monitor_args_log
  #failed_when: monitor-args_log.stdout != ""
