- name: "Update database-trunk sources"
  subversion:
    repo: http://dev.ikono.com.co/svn/database/trunk
    dest: /usr/local/src/ikono/database-trunk/
    username: "{{ svn_username }}"
    password: "{{ svn_password }}"
    checkout: no
    update: yes
    switch: no
    force: yes

- name: "Dump repqueuelog database" # with routines
  shell: mysqldump repqueuelog -u{{ mysql_username }} --default-character-set=utf8 -p{{ mysql_password }} --routines > /tmp/repqueuelog_{{ ansible_date_time.epoch }}.sql
  register: dump_repqueuelog

- name: "Copy update_database.sql file"
  copy:
    src: update_database.sql
    dest: /tmp
    
- name: "Update repqueuelog database"
  shell: mysql repqueuelog -sfu{{ mysql_username }} --default-character-set=utf8 -p{{ mysql_password }} < /tmp/update_database.sql |& tee -a /tmp/update_db_{{ ansible_date_time.epoch }}.log
  ignore_errors: True
  register: update_repqueuelog

- name: "Validate repqueuelog database updated"
  shell: mysql repqueuelog -sfu{{ mysql_username }} --default-character-set=utf8 -p{{ mysql_password }} -e "SELECT column_name FROM information_schema.columns WHERE table_schema='repqueuelog' AND table_name='jos_queuelog_recordings' AND column_name='tags';"
  register: validate_repqueuelog
  failed_when: validate_repqueuelog.stdout != "tags"

- name: "Debuging repqueuelog"
  debug: 
    msg: "{{ update_repqueuelog.stdout_lines }}"
