- name: "Update all packages"
  yum:
    name: '*'
    state: latest
    #exclude: kernel*
  when: ansible_facts['os_family'] == "RedHat"

# - shell: yum -y update
#   register: update

# - debug: msg="{{ update.results }}"
# - debug: msg="{{ update.stdout_lines }}"

# - apt:
#     name: '*'
#     state: latest
#     #exclude: kernel*
#   when: ansible_facts['os_family'] == "Debian"