---
- name: "YUM Packages"
  #hosts: all
  hosts: all:!B2BUA
  tasks:
    - name: Add Irontec repository
      yum_repository:
        name: irontec
        file: irontec
        description: Irontec RPMs repository
        baseurl: http://packages.irontec.com/centos/$releasever/$basearch/
        enabled: yes
        gpgcheck: no
        state: present

    - import_tasks: ../tasks/upgrade-all-packages.yml
